### ISSUE TITLE
bindgen can fail on dual binary and library crates

### ISSUE THREAD

**Issue by tari** [rukai/cargo-run-wasm#13]
If there is a crate in a workspace that can be built as either a binary or a library and has required features, run-wasm will fail if those features are disabled.

Crate manifest:
```toml
[package]
name = "mycrate"

[[bin]]
name = "mycrate"
required-features = ["example-feature"]

[lib]

[features]
example-feature = []
```

Then run-wasm:
```
$ cargo run-wasm mycrate
    Finished release [optimized] target(s) in 0.31s
     Running `target\release\run-wasm.exe mycrate`
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed reading '...target/wasm-examples-target/wasm32-unknown-unknown\debug\mycrate.wasm'

Caused by:
    The system cannot find the file specified. (os error 2)', $HOME\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-run-wasm-0.2.0\src\lib.rs:174:10
```

This appears to be because run-wasm simply runs `cargo build`, which will build the library target only; `cargo build` is documented to omit binary targets if required features are not enabled.

I think doing `cargo run --bin mycrate` will work correctly in all cases by failing the build if the required feature is not enabled, and otherwise working the same as without `--bin` because `run-wasm` assumes the binary target to run has the same name as the crate. As a workaround I can also adjust `.cargo/config` to always enable the feature that's required by this binary when doing `run-wasm`, but I believe changing run-wasm to pass `--bin` to cargo is a more general solution with no downside.

**Comment by rukai** [comment]
I've made a PR to address this: https://github.com/rukai/cargo-run-wasm/pull/16
I'll have to look over it again with a fresh mind eventually, in the mean time feel free to try it out and let me know if it solves your problem.

**Comment by rukai** [comment]
I believe this is resolved by https://github.com/rukai/cargo-run-wasm/pull/16
