### ISSUE TITLE
`cargo run-wasm` fails with custom build profiles

### ISSUE THREAD

**Issue by edusporto** [rukai/cargo-run-wasm#23]
Hi!

I wrote a custom build profile to a project of mine targeting the smallest binary output possible.

The build profile is defined as the following:
```toml
[profile.release-small]
inherits = "release"
strip = true
lto = true
panic = "abort"
```

When trying to use the following command to run my project:

```bash
cargo run-wasm --profile release-small --bin [BIN_NAME]
```

I get the following error:

```
There is no binary at "[PATH_TO_REPO]/target/wasm-examples-target/wasm32-unknown-unknown/debug/nes.wasm", maybe you used `--package NAME` on a package that has no binary?
```

It seems that the command defaults the profile to `debug` when trying to run the program.

Thanks!

**Comment by rukai** [comment]
Thanks for the report!
It looks like there is fairly straightforward fix for this, I'll make a PR for it now.

**Comment by rukai** [comment]
Can you give https://github.com/rukai/cargo-run-wasm/pull/26 a go and let me know if it solves your problem?

**Comment by rukai** [comment]
I recreated your example myself and it works for that so I'll go ahead and land the change.
