### ISSUE TITLE
CargoDirectories::new is broken when using the from_cargo code-path

### ISSUE THREAD

**Issue by StT191** [rukai/cargo-run-wasm#30]
Dear Rukai,

thank you for your effort in releasing the new version. Unfortunately `CargoDirectories::new(...)` got a small regression. You are mutating the `manifest_dir` variable in the loop while traversing up the file system. However later on you pass it to `CargoDirectories::from_cargo(...)` when it should be the original value.

Please fix. Kind Regards.

**Comment by rukai** [comment]
Ooops, your right!
Thankyou for the report and detailed fix.
