### ISSUE TITLE
Referencing static assets

### ISSUE THREAD

**Issue by sampullman** [rukai/cargo-run-wasm#44]
We're considering `cargo-run-wasm` to run examples, and each one references different static assets (images, shaders, etc). Is there a clean way to do this without copying files to `target/wasm-examples/my-example` at runtime? Symlinking the example resources folder is one way, but doesn't work on Windows.

I don't see an easy way to do this with `devserver_lib` so it's probably outside the scope of `cargo-run-wasm`, but figured it's worth asking to see if anybody has solved this cleanly.

Thanks for the great project!

**Comment by rukai** [comment]
Unfortunately there isnt, cargo-run-wasm assumes that your application is entirely self-contained within the wasm file output by cargo.

**Comment by sampullman** [comment]
Thanks for the reply!
